### ISSUE TITLE
Possible missing public images for "gke.gcr.io/csi-node-driver-registrar:win-v1"

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-csi/csi-driver-smb#148]
**What happened**:

Im trying to run 0.4 with the csi-proxy YAMLs, but running into some issues.

Seems like getting up and running w/ csi-proxy doesnt work for me.  Could be a n00b error.  But i thought it was odd that it was trying to dial `unix C://` on a windows node.

**without CSI proxy running** 
```
Events:                                                                                                     
  Type     Reason       Age                From               Message                                                                              
  ----     ------       ----               ----               -------                                                                      
  Normal   Scheduled    47s                default-scheduler  Successfully assigned default/iis-site-windows-55566495cc-78sws to win-h0c364gqvjh
  Warning  FailedMount  31s (x4 over 46s)  kubelet            MountVolume.MountDevice failed for volume "pvc-406947d6-29a0-4388-808f-4d2bcedccba6" : rpc error: code = Unavailable desc = connection e
rror: desc = "transport: Error while dialing dial unix C:\\\\var\\\\lib\\\\kubelet\\\\plugins\\\\smb.csi.k8s.io\\\\csi.sock: connect: No connection could be made because the target machine actively 
refused it."                                                                                                                                                                                          
  Warning  FailedMount  15s (x3 over 47s)  kubelet            MountVolume.MountDevice failed for volume "pvc-406947d6-29a0-4388-808f-4d2bcedccba6" : rpc error: code = Unavailable desc = transport is
 closing   
``` 
This eventually turns into:
```
  Warning  FailedMount  7s    kubelet            MountVolume.MountDevice failed for volume "pvc-406947d6-29a0-4388-808f-4d2bcedccba6" : rpc error: code = Unavailable desc = transport is closing
```

Which i suppose is related to the fact that my csi proxy isnt happy.

**What you expected to happen**:

The CSI driver wouldnt try to mount a unix:// socket in a windows container... 

**How to reproduce it**:

Am running csi-driver-smb with/or without the csi-proxy stuff.  Either way it seems like mounting of volumes fails (for me at least).  There may be some defaults i didnt set propery.. 

  
**Anything else we need to know?**:

**Environment**:  windows
- CSI Driver version: 0.4.0
- Kubernetes version (use `kubectl version`): 1.19
- OS (e.g. from /etc/os-release): windows

**Comment by jayunit100** [comment]
After installing the csi-proxy, i got a different error:

```
I1111 12:09:32.158811   33624 nodeserver.go:195] targetPath(\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-406947d6-29a0-4388-808f-4d2bcedccba6\globalmount) volumeID(pvc-406947d6-29a0-4388-808f-4d2bcedccba6) context(map[createSubDir:false source://smb-server.default.svc.cluster.local/share storage.kubernetes.io/csiProvisionerIdentity:1605115216184-8081-smb.csi.k8s.io]) mountflags([dir_mode=
0777 file_mode=0777 uid=1001 gid=1001]) mountOptions([AZURE\USERNAME])
I1111 12:09:32.158811   33624 safe_mounter_windows.go:147] IsLikelyNotMountPoint: \var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-406947d6-29a0-4388-808f-4d2bcedccba6\globalmount
I1111 12:09:32.158811   33624 safe_mounter_windows.go:205] Exists path: \var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-406947d6-29a0-4388-808f-4d2bcedccba6\globalmount
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x897f8c]

goroutine 49 [running]:
github.com/kubernetes-csi/csi-driver-smb/pkg/mounter.(*CSIProxyMounter).ExistsPath(0xc0001b0140, 0xc00003a5b0, 0x62, 0x0, 0xa5a6e7, 0x19)
        /root/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/mounter/safe_mounter_windows.go:210 +0x17c
github.com/kubernetes-csi/csi-driver-smb/pkg/mounter.(*CSIProxyMounter).IsLikelyNotMountPoint(0xc0001b0140, 0xc00003a5b0, 0x62, 0x0, 0x0, 0xa36540)
        /root/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/mounter/safe_mounter_windows.go:148 +0xdf
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).ensureMountPoint(0xc000106280, 0xc00003a5b0, 0x62, 0x0, 0xa71b49, 0x47)
        /root/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/nodeserver.go:274 +0x70

```

Which seems to imply maybe, since im not in Azure, this wont work ?

**Comment by jayunit100** [comment]
so, if i look at the csi-smb-node logs, i see

```
Compiler: gc                                                                                                                                                                                                                              [0/1001]
Driver Name: smb.csi.k8s.io
Driver Version: v0.4.0
Git Commit: 9a9f0e8e5158389dec157e2195dce71b78247630
Go Version: go1.14.4
Platform: windows/amd64

Streaming logs below:
I1111 12:19:10.077958   36004 driver.go:93] Enabling controller service capability: CREATE_DELETE_VOLUME
I1111 12:19:10.077958   36004 driver.go:112] Enabling volume access mode: SINGLE_NODE_WRITER
I1111 12:19:10.077958   36004 driver.go:112] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I1111 12:19:10.077958   36004 driver.go:112] Enabling volume access mode: MULTI_NODE_READER_ONLY
I1111 12:19:10.077958   36004 driver.go:112] Enabling volume access mode: MULTI_NODE_SINGLE_WRITER
I1111 12:19:10.077958   36004 driver.go:112] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I1111 12:19:10.077958   36004 driver.go:103] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I1111 12:19:10.079945   36004 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"C:\\\\csi\\\\csi.sock", Net:"unix"}
I1111 12:19:42.427905   36004 utils.go:107] GRPC call: /csi.v1.Node/NodeGetCapabilities
I1111 12:19:42.427905   36004 utils.go:108] GRPC request: {}
I1111 12:19:42.427905   36004 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I1111 12:19:42.433033   36004 utils.go:107] GRPC call: /csi.v1.Node/NodeStageVolume
I1111 12:19:42.433033   36004 utils.go:108] GRPC request: {"secrets":"***stripped***","staging_target_path":"\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-406947d6-29a0-4388-808f-4d2bcedccba6\\globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["dir_mode=0777","file_mode=0777","uid=1001","gid=1001"]}},"access_mode":{"mode":1}},"volume_context":{"createSubDir":"false","source":"//smb-server.default.svc.cluster.local/share","storage.
kubernetes.io/csiProvisionerIdentity":"1605115216184-8081-smb.csi.k8s.io"},"volume_id":"pvc-406947d6-29a0-4388-808f-4d2bcedccba6"}
I1111 12:19:42.434146   36004 nodeserver.go:195] targetPath(\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-406947d6-29a0-4388-808f-4d2bcedccba6\globalmount) volumeID(pvc-406947d6-29a0-4388-808f-4d2bcedccba6) context(map[createSubDir:false
source://smb-server.default.svc.cluster.local/share storage.kubernetes.io/csiProvisionerIdentity:1605115216184-8081-smb.csi.k8s.io]) mountflags([dir_mode=0777 file_mode=0777 uid=1001 gid=1001]) mountOptions([AZURE\USERNAME])
I1111 12:19:42.434146   36004 safe_mounter_windows.go:147] IsLikelyNotMountPoint: \var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-406947d6-29a0-4388-808f-4d2bcedccba6\globalmount
I1111 12:19:42.434146   36004 safe_mounter_windows.go:205] Exists path: \var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-406947d6-29a0-4388-808f-4d2bcedccba6\globalmount
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x897f8c]

goroutine 39 [running]:
github.com/kubernetes-csi/csi-driver-smb/pkg/mounter.(*CSIProxyMounter).ExistsPath(0xc00008e800, 0xc00003a540, 0x62, 0x0, 0xa5a6e7, 0x19)
        /root/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/mounter/safe_mounter_windows.go:210 +0x17c
github.com/kubernetes-csi/csi-driver-smb/pkg/mounter.(*CSIProxyMounter).IsLikelyNotMountPoint(0xc00008e800, 0xc00003a540, 0x62, 0x0, 0x0, 0xa36540)
        /root/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/mounter/safe_mounter_windows.go:148 +0xdf
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).ensureMountPoint(0xc00009a080, 0xc00003a540, 0x62, 0x0, 0xa71b49, 0x47)
        /root/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/nodeserver.go:274 +0x70
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).NodeStageVolume(0xc00009a080, 0xb25320, 0xc00026fcb0, 0xc0002de720, 0xc00009a080, 0xed9b77, 0xc000095420)
```

**Comment by jayunit100** [comment]
So, it looks like my daemonset wasnt runningbc i never created the required service account .

After creating `csi-node-sa`, i think saw:

```
  Failed to pull image "gke.gcr.io/csi-node-driver-registrar:win-v1": rpc error: code = Unknown desc = Error response from daemon: manifest for gke.gcr.io/csi-node-driver-registrar:win-v1 not found: manifest unknown: Failed to fetch "win-v1" from request "/v2/csi-node-driver-registrar/manifests/win-v1".
```

Which maybe is implying that we dont have the images up to date ?

**Comment by jayunit100** [comment]
actually this seems like maybe its a csi-smb issue, since my csi-driver-smb seems to be healthy
