### ISSUE TITLE
install as host process on windows node and not requiring csi-proxy

### ISSUE THREAD

**Issue by himanshuz2** [kubernetes-csi/csi-driver-smb#481]
**Is your feature request related to a problem?/Why is this needed**
with hostprocess now available, csi-proxy should not be needed to run this driver on windows nodes

**Describe the solution you'd like in detail**
a daemonset that can deploy this driver on every windows node on the cluster. 

**Describe alternatives you've considered**
login to every added windows node and install csi-proxy using the methods described
modify the base image for windows node pool to install csi-proxy

**Additional context**

**Comment by andyzhangx** [comment]
related to this PR: https://github.com/kubernetes-csi/csi-proxy/pull/179

**Comment by himanshuz2** [comment]
Found the yaml file to install csi-proxy
https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/templates/addons/windows/csi-proxy

**Comment by andyzhangx** [comment]
> Found the yaml file to install csi-proxy https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/templates/addons/windows/csi-proxy

@himanshuz2 so run following command on k8s 1.23+ cluster would work?
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/addons/windows/csi-proxy/csi-proxy.yaml
```

**Comment by himanshuz2** [comment]
> > Found the yaml file to install csi-proxy https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/templates/addons/windows/csi-proxy
> 
> @himanshuz2 so run following command on k8s 1.23+ cluster would work?
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/addons/windows/csi-proxy/csi-proxy.yaml
> ```

Yes.

**Comment by Termibg22** [comment]
> > > Found the yaml file to install csi-proxy https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/templates/addons/windows/csi-proxy
> > 
> > 
> > @himanshuz2 so run following command on k8s 1.23+ cluster would work?
> > ```
> > kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/addons/windows/csi-proxy/csi-proxy.yaml
> > ```
> 
> Yes.

When i try to install it on a RKE2 cluster with 2 windows nodes the pod gives the following error:

``
I0907 03:07:19.474978    7664 main.go:64] Starting CSI-Proxy Server ...
I0907 03:07:19.474978    7664 main.go:65] Version: v1.1.1-0-gc16d19a
I0907 03:07:19.474978    7664 main.go:84] Working directories: %v[C:\var\lib\kubelet]
2023-09-07T03:07:19.482378900-07:00 panic: ([]error) 0xc000004c00
2023-09-07T03:07:19.482652900-07:00 
2023-09-07T03:07:19.482652900-07:00 goroutine 1 [running]:
main.main()
2023-09-07T03:07:19.482652900-07:00 	/mnt/vss/_work/1/go/src/github.com/kubernetes-csi/csi-proxy/cmd/csi-proxy/main.go:73 +0x1fd
``

**Comment by luisxkimo** [comment]
Same error here trying to deploy in a Windows node:

```
I1024 01:16:18.517890    9912 main.go:64] Starting CSI-Proxy Server ...
I1024 01:16:18.517890    9912 main.go:65] Version: v1.1.2-0-g015225a
I1024 01:16:18.517890    9912 main.go:84] Working directories: %v[C:\var\lib\kubelet]
panic: (]error) 0xc000008c18

goroutine 1 [running]:
main.main()
    /go/csi-proxy/cmd/csi-proxy/main.go:73 +0x20d
Stream closed EOF for kube-system/csi-proxy-xtvkf (csi-proxy)

```

**Comment by andyzhangx** [comment]
windows hostprocess deployment is already supported by default on master branch, will publish v1.17.0 release.
