### ISSUE TITLE
enable sanity test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#6]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

refer to following link to set up a containerized samba in CI environment:
https://github.com/dperson/samba

```
# make sanity-test
CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-X github.com/csi-driver/csi-driver-smb/pkg/smb.driverVersion=v0.1.0 -X github.com/csi-driver/csi-driver-smb/pkg/smb.gitCommit=26289639ca62e6f637b49b48c7291ce50e61648d -X github.com/csi-driver/csi-driver-smb/pkg/smb.buildDate=2020-05-11T03:17:55Z -s -w -extldflags '-static'" -o _output/smbplugin ./pkg/smbplugin
go test -v -timeout=10m ./test/sanity
=== RUN   TestSanity
--- FAIL: TestSanity (0.00s)
    sanity_test.go:43:
                Error Trace:    sanity_test.go:43
                Error:          Received unexpected error:
                                If you are running tests locally, you will need to set the following env vars: $TENANT_ID, $SUBSCRIPTION_ID, $AAD_CLIENT_ID, $AAD_CLIENT_SECRET, $RESOURCE_GROUP, $LOCATION
                Test:           TestSanity
    sanity_test.go:44:
                Error Trace:    sanity_test.go:44
                Error:          Expected value not to be nil.
                Test:           TestSanity
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x884f48]

goroutine 7 [running]:
testing.tRunner.func1(0xc0000f8200)
        /usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x905920, 0xda8490)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/csi-driver/csi-driver-smb/test/sanity.TestSanity(0xc0000f8200)
        /root/go/src/github.com/csi-driver/csi-driver-smb/test/sanity/sanity_test.go:49 +0x198
testing.tRunner(0xc0000f8200, 0x9be640)
        /usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:960 +0x350
FAIL    github.com/csi-driver/csi-driver-smb/test/sanity        0.008s
FAIL

```

**Describe alternatives you've considered**

**Additional context**

**Comment by Sakuralbj** [comment]
I'll do it.
